// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbybhdhfpemgnwtnvohv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndieWJoZGhmcGVtZ253dG52b2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzU3NzksImV4cCI6MjA2NTg1MTc3OX0.yC6zjH5K5bKkaupqeBpN4NWSt8zlyZ3cvk6uCyMODaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});